name: Build and Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - 'memory-bank/**'
      - '*.md'
      - 'docs/**'
      - '.claude/**'
      - 'CLAUDE.md'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry Export Plugin
        run: |
          poetry self add poetry-plugin-export

      - name: Export requirements.txt
        run: |
          poetry export --without dev -f requirements.txt -o requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot:latest
            ${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd /opt/telegram-voice2text-bot || exit 1

            # Pull latest code (for docker-compose.yml updates)
            git pull origin main

            # Create .env file with secrets
            cat > .env <<EOF
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            BOT_MODE=polling

            # Transcription Provider Configuration
            WHISPER_PROVIDERS=["faster-whisper"]
            WHISPER_ROUTING_STRATEGY=single
            PRIMARY_PROVIDER=faster-whisper

            # FasterWhisper Production Configuration (medium/int8/beam1)
            FASTER_WHISPER_MODEL_SIZE=medium
            FASTER_WHISPER_DEVICE=cpu
            FASTER_WHISPER_COMPUTE_TYPE=int8
            FASTER_WHISPER_BEAM_SIZE=1
            FASTER_WHISPER_VAD_FILTER=true

            # Database
            DATABASE_URL=sqlite+aiosqlite:////app/data/bot.db

            # Processing
            MAX_QUEUE_SIZE=100
            MAX_CONCURRENT_WORKERS=3
            TRANSCRIPTION_TIMEOUT=120
            MAX_VOICE_DURATION_SECONDS=300

            # Quota
            DEFAULT_DAILY_QUOTA_SECONDS=60

            # Logging
            LOG_LEVEL=WARNING

            # Benchmark Mode
            BENCHMARK_MODE=false
            EOF

            # Pull new Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot:${{ github.sha }}

            # Tag as latest
            docker tag ${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot:${{ github.sha }} \
                       ${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot:latest

            # Update IMAGE_NAME in .env for docker-compose
            echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot:latest" >> .env

            # Create required directories (if not exist)
            mkdir -p data logs

            # Set permissions for appuser inside container (UID 1000)
            chown -R 1000:1000 data logs

            # Rolling update with zero downtime
            docker compose -f docker-compose.prod.yml up -d --no-deps bot

            # Wait for container to be healthy
            echo "⏳ Waiting for health check..."
            sleep 15

            # Check if container is healthy
            CONTAINER_STATUS=$(docker inspect --format='{{.State.Health.Status}}' telegram-voice2text-bot 2>/dev/null || echo "unknown")

            if [ "$CONTAINER_STATUS" != "healthy" ] && [ "$CONTAINER_STATUS" != "unknown" ]; then
              echo "❌ Health check failed! Container status: $CONTAINER_STATUS"
              docker compose -f docker-compose.prod.yml logs --tail=50 bot
              exit 1
            fi

            # Show status
            echo "✅ Deployment successful!"
            docker compose -f docker-compose.prod.yml ps

            # Cleanup old images (keep last 3)
            docker images ${{ secrets.DOCKER_USERNAME }}/telegram-voice2text-bot --format "{{.ID}} {{.CreatedAt}}" | \
              tail -n +4 | awk '{print $1}' | xargs -r docker rmi || true
